// Países del mundo (en español) con su código ISO (para imágenes de bandera) y
// su código telefónico. Venezuela primero; el resto en orden alfabético.
//
// Nota: usamos imágenes de bandera (flagcdn) en vez de emoji, porque Windows
// no renderiza los emoji de banderas (muestra las letras del país).
export interface Pais {
  nombre: string
  iso: string // código ISO-3166 alfa-2 en minúscula (para flagcdn)
  codigo: string // código telefónico internacional
}

export const PAISES_MUNDO: Pais[] = [
  { nombre: 'Venezuela', iso: 've', codigo: '+58' },
  { nombre: 'Afganistán', iso: 'af', codigo: '+93' },
  { nombre: 'Albania', iso: 'al', codigo: '+355' },
  { nombre: 'Alemania', iso: 'de', codigo: '+49' },
  { nombre: 'Andorra', iso: 'ad', codigo: '+376' },
  { nombre: 'Angola', iso: 'ao', codigo: '+244' },
  { nombre: 'Antigua y Barbuda', iso: 'ag', codigo: '+1' },
  { nombre: 'Arabia Saudita', iso: 'sa', codigo: '+966' },
  { nombre: 'Argelia', iso: 'dz', codigo: '+213' },
  { nombre: 'Argentina', iso: 'ar', codigo: '+54' },
  { nombre: 'Armenia', iso: 'am', codigo: '+374' },
  { nombre: 'Aruba', iso: 'aw', codigo: '+297' },
  { nombre: 'Australia', iso: 'au', codigo: '+61' },
  { nombre: 'Austria', iso: 'at', codigo: '+43' },
  { nombre: 'Azerbaiyán', iso: 'az', codigo: '+994' },
  { nombre: 'Bahamas', iso: 'bs', codigo: '+1' },
  { nombre: 'Bangladés', iso: 'bd', codigo: '+880' },
  { nombre: 'Barbados', iso: 'bb', codigo: '+1' },
  { nombre: 'Baréin', iso: 'bh', codigo: '+973' },
  { nombre: 'Bélgica', iso: 'be', codigo: '+32' },
  { nombre: 'Belice', iso: 'bz', codigo: '+501' },
  { nombre: 'Benín', iso: 'bj', codigo: '+229' },
  { nombre: 'Bielorrusia', iso: 'by', codigo: '+375' },
  { nombre: 'Bolivia', iso: 'bo', codigo: '+591' },
  { nombre: 'Bosnia y Herzegovina', iso: 'ba', codigo: '+387' },
  { nombre: 'Botsuana', iso: 'bw', codigo: '+267' },
  { nombre: 'Brasil', iso: 'br', codigo: '+55' },
  { nombre: 'Brunéi', iso: 'bn', codigo: '+673' },
  { nombre: 'Bulgaria', iso: 'bg', codigo: '+359' },
  { nombre: 'Burkina Faso', iso: 'bf', codigo: '+226' },
  { nombre: 'Burundi', iso: 'bi', codigo: '+257' },
  { nombre: 'Bután', iso: 'bt', codigo: '+975' },
  { nombre: 'Cabo Verde', iso: 'cv', codigo: '+238' },
  { nombre: 'Camboya', iso: 'kh', codigo: '+855' },
  { nombre: 'Camerún', iso: 'cm', codigo: '+237' },
  { nombre: 'Canadá', iso: 'ca', codigo: '+1' },
  { nombre: 'Catar', iso: 'qa', codigo: '+974' },
  { nombre: 'Chad', iso: 'td', codigo: '+235' },
  { nombre: 'Chile', iso: 'cl', codigo: '+56' },
  { nombre: 'China', iso: 'cn', codigo: '+86' },
  { nombre: 'Chipre', iso: 'cy', codigo: '+357' },
  { nombre: 'Colombia', iso: 'co', codigo: '+57' },
  { nombre: 'Comoras', iso: 'km', codigo: '+269' },
  { nombre: 'Corea del Norte', iso: 'kp', codigo: '+850' },
  { nombre: 'Corea del Sur', iso: 'kr', codigo: '+82' },
  { nombre: 'Costa de Marfil', iso: 'ci', codigo: '+225' },
  { nombre: 'Costa Rica', iso: 'cr', codigo: '+506' },
  { nombre: 'Croacia', iso: 'hr', codigo: '+385' },
  { nombre: 'Cuba', iso: 'cu', codigo: '+53' },
  { nombre: 'Curazao', iso: 'cw', codigo: '+599' },
  { nombre: 'Dinamarca', iso: 'dk', codigo: '+45' },
  { nombre: 'Dominica', iso: 'dm', codigo: '+1' },
  { nombre: 'Ecuador', iso: 'ec', codigo: '+593' },
  { nombre: 'Egipto', iso: 'eg', codigo: '+20' },
  { nombre: 'El Salvador', iso: 'sv', codigo: '+503' },
  { nombre: 'Emiratos Árabes Unidos', iso: 'ae', codigo: '+971' },
  { nombre: 'Eritrea', iso: 'er', codigo: '+291' },
  { nombre: 'Eslovaquia', iso: 'sk', codigo: '+421' },
  { nombre: 'Eslovenia', iso: 'si', codigo: '+386' },
  { nombre: 'España', iso: 'es', codigo: '+34' },
  { nombre: 'Estados Unidos', iso: 'us', codigo: '+1' },
  { nombre: 'Estonia', iso: 'ee', codigo: '+372' },
  { nombre: 'Esuatini', iso: 'sz', codigo: '+268' },
  { nombre: 'Etiopía', iso: 'et', codigo: '+251' },
  { nombre: 'Filipinas', iso: 'ph', codigo: '+63' },
  { nombre: 'Finlandia', iso: 'fi', codigo: '+358' },
  { nombre: 'Fiyi', iso: 'fj', codigo: '+679' },
  { nombre: 'Francia', iso: 'fr', codigo: '+33' },
  { nombre: 'Gabón', iso: 'ga', codigo: '+241' },
  { nombre: 'Gambia', iso: 'gm', codigo: '+220' },
  { nombre: 'Georgia', iso: 'ge', codigo: '+995' },
  { nombre: 'Ghana', iso: 'gh', codigo: '+233' },
  { nombre: 'Granada', iso: 'gd', codigo: '+1' },
  { nombre: 'Grecia', iso: 'gr', codigo: '+30' },
  { nombre: 'Guatemala', iso: 'gt', codigo: '+502' },
  { nombre: 'Guyana', iso: 'gy', codigo: '+592' },
  { nombre: 'Guinea', iso: 'gn', codigo: '+224' },
  { nombre: 'Guinea-Bisáu', iso: 'gw', codigo: '+245' },
  { nombre: 'Guinea Ecuatorial', iso: 'gq', codigo: '+240' },
  { nombre: 'Haití', iso: 'ht', codigo: '+509' },
  { nombre: 'Honduras', iso: 'hn', codigo: '+504' },
  { nombre: 'Hungría', iso: 'hu', codigo: '+36' },
  { nombre: 'India', iso: 'in', codigo: '+91' },
  { nombre: 'Indonesia', iso: 'id', codigo: '+62' },
  { nombre: 'Irak', iso: 'iq', codigo: '+964' },
  { nombre: 'Irán', iso: 'ir', codigo: '+98' },
  { nombre: 'Irlanda', iso: 'ie', codigo: '+353' },
  { nombre: 'Islandia', iso: 'is', codigo: '+354' },
  { nombre: 'Islas Marshall', iso: 'mh', codigo: '+692' },
  { nombre: 'Islas Salomón', iso: 'sb', codigo: '+677' },
  { nombre: 'Israel', iso: 'il', codigo: '+972' },
  { nombre: 'Italia', iso: 'it', codigo: '+39' },
  { nombre: 'Jamaica', iso: 'jm', codigo: '+1' },
  { nombre: 'Japón', iso: 'jp', codigo: '+81' },
  { nombre: 'Jordania', iso: 'jo', codigo: '+962' },
  { nombre: 'Kazajistán', iso: 'kz', codigo: '+7' },
  { nombre: 'Kenia', iso: 'ke', codigo: '+254' },
  { nombre: 'Kirguistán', iso: 'kg', codigo: '+996' },
  { nombre: 'Kiribati', iso: 'ki', codigo: '+686' },
  { nombre: 'Kuwait', iso: 'kw', codigo: '+965' },
  { nombre: 'Laos', iso: 'la', codigo: '+856' },
  { nombre: 'Lesoto', iso: 'ls', codigo: '+266' },
  { nombre: 'Letonia', iso: 'lv', codigo: '+371' },
  { nombre: 'Líbano', iso: 'lb', codigo: '+961' },
  { nombre: 'Liberia', iso: 'lr', codigo: '+231' },
  { nombre: 'Libia', iso: 'ly', codigo: '+218' },
  { nombre: 'Liechtenstein', iso: 'li', codigo: '+423' },
  { nombre: 'Lituania', iso: 'lt', codigo: '+370' },
  { nombre: 'Luxemburgo', iso: 'lu', codigo: '+352' },
  { nombre: 'Macedonia del Norte', iso: 'mk', codigo: '+389' },
  { nombre: 'Madagascar', iso: 'mg', codigo: '+261' },
  { nombre: 'Malasia', iso: 'my', codigo: '+60' },
  { nombre: 'Malaui', iso: 'mw', codigo: '+265' },
  { nombre: 'Maldivas', iso: 'mv', codigo: '+960' },
  { nombre: 'Malí', iso: 'ml', codigo: '+223' },
  { nombre: 'Malta', iso: 'mt', codigo: '+356' },
  { nombre: 'Marruecos', iso: 'ma', codigo: '+212' },
  { nombre: 'Mauricio', iso: 'mu', codigo: '+230' },
  { nombre: 'Mauritania', iso: 'mr', codigo: '+222' },
  { nombre: 'México', iso: 'mx', codigo: '+52' },
  { nombre: 'Micronesia', iso: 'fm', codigo: '+691' },
  { nombre: 'Moldavia', iso: 'md', codigo: '+373' },
  { nombre: 'Mónaco', iso: 'mc', codigo: '+377' },
  { nombre: 'Mongolia', iso: 'mn', codigo: '+976' },
  { nombre: 'Montenegro', iso: 'me', codigo: '+382' },
  { nombre: 'Mozambique', iso: 'mz', codigo: '+258' },
  { nombre: 'Myanmar', iso: 'mm', codigo: '+95' },
  { nombre: 'Namibia', iso: 'na', codigo: '+264' },
  { nombre: 'Nauru', iso: 'nr', codigo: '+674' },
  { nombre: 'Nepal', iso: 'np', codigo: '+977' },
  { nombre: 'Nicaragua', iso: 'ni', codigo: '+505' },
  { nombre: 'Níger', iso: 'ne', codigo: '+227' },
  { nombre: 'Nigeria', iso: 'ng', codigo: '+234' },
  { nombre: 'Noruega', iso: 'no', codigo: '+47' },
  { nombre: 'Nueva Zelanda', iso: 'nz', codigo: '+64' },
  { nombre: 'Omán', iso: 'om', codigo: '+968' },
  { nombre: 'Países Bajos', iso: 'nl', codigo: '+31' },
  { nombre: 'Pakistán', iso: 'pk', codigo: '+92' },
  { nombre: 'Palaos', iso: 'pw', codigo: '+680' },
  { nombre: 'Palestina', iso: 'ps', codigo: '+970' },
  { nombre: 'Panamá', iso: 'pa', codigo: '+507' },
  { nombre: 'Papúa Nueva Guinea', iso: 'pg', codigo: '+675' },
  { nombre: 'Paraguay', iso: 'py', codigo: '+595' },
  { nombre: 'Perú', iso: 'pe', codigo: '+51' },
  { nombre: 'Polonia', iso: 'pl', codigo: '+48' },
  { nombre: 'Portugal', iso: 'pt', codigo: '+351' },
  { nombre: 'Puerto Rico', iso: 'pr', codigo: '+1' },
  { nombre: 'Reino Unido', iso: 'gb', codigo: '+44' },
  { nombre: 'República Centroafricana', iso: 'cf', codigo: '+236' },
  { nombre: 'República Checa', iso: 'cz', codigo: '+420' },
  { nombre: 'República del Congo', iso: 'cg', codigo: '+242' },
  { nombre: 'República Democrática del Congo', iso: 'cd', codigo: '+243' },
  { nombre: 'República Dominicana', iso: 'do', codigo: '+1' },
  { nombre: 'Ruanda', iso: 'rw', codigo: '+250' },
  { nombre: 'Rumania', iso: 'ro', codigo: '+40' },
  { nombre: 'Rusia', iso: 'ru', codigo: '+7' },
  { nombre: 'Samoa', iso: 'ws', codigo: '+685' },
  { nombre: 'San Cristóbal y Nieves', iso: 'kn', codigo: '+1' },
  { nombre: 'San Marino', iso: 'sm', codigo: '+378' },
  { nombre: 'San Vicente y las Granadinas', iso: 'vc', codigo: '+1' },
  { nombre: 'Santa Lucía', iso: 'lc', codigo: '+1' },
  { nombre: 'Santo Tomé y Príncipe', iso: 'st', codigo: '+239' },
  { nombre: 'Senegal', iso: 'sn', codigo: '+221' },
  { nombre: 'Serbia', iso: 'rs', codigo: '+381' },
  { nombre: 'Seychelles', iso: 'sc', codigo: '+248' },
  { nombre: 'Sierra Leona', iso: 'sl', codigo: '+232' },
  { nombre: 'Singapur', iso: 'sg', codigo: '+65' },
  { nombre: 'Siria', iso: 'sy', codigo: '+963' },
  { nombre: 'Somalia', iso: 'so', codigo: '+252' },
  { nombre: 'Sri Lanka', iso: 'lk', codigo: '+94' },
  { nombre: 'Sudáfrica', iso: 'za', codigo: '+27' },
  { nombre: 'Sudán', iso: 'sd', codigo: '+249' },
  { nombre: 'Sudán del Sur', iso: 'ss', codigo: '+211' },
  { nombre: 'Suecia', iso: 'se', codigo: '+46' },
  { nombre: 'Suiza', iso: 'ch', codigo: '+41' },
  { nombre: 'Surinam', iso: 'sr', codigo: '+597' },
  { nombre: 'Tailandia', iso: 'th', codigo: '+66' },
  { nombre: 'Tanzania', iso: 'tz', codigo: '+255' },
  { nombre: 'Tayikistán', iso: 'tj', codigo: '+992' },
  { nombre: 'Timor Oriental', iso: 'tl', codigo: '+670' },
  { nombre: 'Togo', iso: 'tg', codigo: '+228' },
  { nombre: 'Tonga', iso: 'to', codigo: '+676' },
  { nombre: 'Trinidad y Tobago', iso: 'tt', codigo: '+1' },
  { nombre: 'Túnez', iso: 'tn', codigo: '+216' },
  { nombre: 'Turkmenistán', iso: 'tm', codigo: '+993' },
  { nombre: 'Turquía', iso: 'tr', codigo: '+90' },
  { nombre: 'Tuvalu', iso: 'tv', codigo: '+688' },
  { nombre: 'Ucrania', iso: 'ua', codigo: '+380' },
  { nombre: 'Uganda', iso: 'ug', codigo: '+256' },
  { nombre: 'Uruguay', iso: 'uy', codigo: '+598' },
  { nombre: 'Uzbekistán', iso: 'uz', codigo: '+998' },
  { nombre: 'Vanuatu', iso: 'vu', codigo: '+678' },
  { nombre: 'Vietnam', iso: 'vn', codigo: '+84' },
  { nombre: 'Yemen', iso: 'ye', codigo: '+967' },
  { nombre: 'Yibuti', iso: 'dj', codigo: '+253' },
  { nombre: 'Zambia', iso: 'zm', codigo: '+260' },
  { nombre: 'Zimbabue', iso: 'zw', codigo: '+263' },
]

const POR_NOMBRE: Record<string, Pais> = Object.fromEntries(
  PAISES_MUNDO.map((p) => [p.nombre, p]),
)

/** Código ISO de un país por su nombre ('' si no se conoce). */
export function isoDe(pais: string): string {
  return POR_NOMBRE[pais]?.iso ?? ''
}
