// Lista de países del mundo (en español) para registrar y filtrar centros de
// acopio. Venezuela primero por ser el foco de la plataforma.
export const PAISES_MUNDO = [
  'Venezuela',
  'Argentina',
  'Bolivia',
  'Brasil',
  'Canadá',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Ecuador',
  'El Salvador',
  'España',
  'Estados Unidos',
  'Francia',
  'Guatemala',
  'Honduras',
  'Italia',
  'México',
  'Nicaragua',
  'Panamá',
  'Paraguay',
  'Perú',
  'Portugal',
  'Puerto Rico',
  'Reino Unido',
  'República Dominicana',
  'Uruguay',
  'Alemania',
  'Australia',
  'Austria',
  'Bélgica',
  'Suiza',
  'Países Bajos',
  'Noruega',
  'Suecia',
  'Dinamarca',
  'Irlanda',
  'Japón',
  'China',
  'Trinidad y Tobago',
  'Aruba',
  'Curazao',
  'Otro',
] as const
